# Generated by Django 3.1.7 on 2021-11-15 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20211115_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAllProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Published video',
                'verbose_name_plural': 'Published videos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('videos.video',),
        ),
        migrations.AlterModelOptions(
            name='videoproxy',
            options={'verbose_name': 'All video', 'verbose_name_plural': 'All videos'},
        ),
    ]
