# Generated by Django 3.1.7 on 2021-11-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20211115_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoallproxy',
            options={'verbose_name': 'All video', 'verbose_name_plural': 'All videos'},
        ),
        migrations.AlterModelOptions(
            name='videopublishedproxy',
            options={'verbose_name': 'Published video', 'verbose_name_plural': 'Published videos'},
        ),
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Publish'), ('DR', 'Draft')], default='DR', max_length=2),
        ),
    ]
